export {
  getPlatformConfig,
  clearPlatformConfigCache,
  publicPlatformView,
  type EnvironmentProfile,
  type FeatureFlags,
  type PlatformConfig,
  type ProviderName,
} from '@/lib/platform/config';
export {
  ROLES,
  PERMISSIONS,
  can,
  canAny,
  featureAllowed,
  isRole,
  permissionsFor,
  policyInstrumentRead,
  policyVoiceAnonymous,
  roleFromEnterpriseUi,
  type FeatureGate,
  type Permission,
  type PolicyDecision,
  type Role,
} from '@/lib/platform/rbac';
export {
  anonymousSession,
  authorizeRequest,
  futureAuthProviders,
  guestSession,
  issueTokenPair,
  resolveSession,
  signAccessToken,
  signRefreshToken,
  verifyAccessToken,
  verifyRefreshToken,
  type AuthProviderKind,
  type AuthorizeResult,
  type FutureAuthProvider,
  type OrganizationRef,
  type PlatformSession,
  type TokenPair,
} from '@/lib/platform/auth';
export {
  endSpan,
  getMetricsSnapshot,
  heartbeat,
  log,
  recordMetric,
  resetMetrics,
  startSpan,
  type LogLevel,
  type MetricName,
  type TraceSpan,
} from '@/lib/platform/observability';
export {
  API_RETRY,
  ERROR_CATALOG,
  platformError,
  reportError,
  withRetry,
  type ErrorCode,
  type ErrorDomain,
  type PlatformError,
  type RecoveryAction,
  type RetryPolicy,
} from '@/lib/platform/errors';
export {
  PRIVACY_RULES,
  SECURITY_HEADERS,
  assertSameOrigin,
  audit,
  clientKey,
  productionSecurityHeaders,
  rateLimit,
  resetRateLimits,
  validateQueryToken,
} from '@/lib/platform/security';
export { platformRoute } from '@/lib/platform/http';
export { liveness, readiness } from '@/lib/platform/health';
